# yaml-language-server: $schema=../../../.schemas/network_jax_fcnet_schema.json
_target_: project.algorithms.jax_example.JaxFcNet
num_classes: ${instance_attr:datamodule.num_classes}
num_features: 256
