# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - run: pip install pre-commit
    - run: pre-commit --version
    - run: pre-commit install
    - run: pre-commit run --all-files
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with pytest (very fast)
      run: pytest -v --shorter-than=1.0
    - name: Test with pytest (fast)
      run: pytest -v
    - name: Test with pytest (with slow tests)
      run: pytest -v -m slow --slow
