defaults:
  - default.yaml
  - override launcher: remote_submitit_slurm
mode: MULTIRUN

run:
  # output directory, generated dynamically on each run
  dir: logs/${hydra.launcher.cluster_hostname}/${name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: logs/${hydra.launcher.cluster_hostname}/${name}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

launcher:
  cluster_hostname: mila
  submitit_folder: "${hydra.sweep.dir}/${.cluster_hostname}/.submitit/%j"
