# enable color logging
defaults:
  - _self_
  - override hydra_logging: disabled
  - override job_logging: disabled
  - override hydra/launcher: submitit_slurm

run:
  # output directory, generated dynamically on each run
  dir: logs/${name}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: logs/${name}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
  subdir: ${hydra.job.num}

verbose: False

#submitit:
  #salloc --gres=gpu:a100:1 -c 6 --mem=32G -t 48:00:00 --partition=unkillable
  #gres: gpu:a100:1
  #cpus_per_gpu: 6
  #mem_per_cpu: 32
  #timeout_min: 180
  #partition: unkillable
