_target_: project.datamodules.text.text_classification.TextClassificationDataModule
data_dir: ${oc.env:SCRATCH,.}/data
hf_dataset_path: glue
task_name: cola
text_fields:
  - "sentence"
tokenizer:
  _target_: transformers.models.auto.tokenization_auto.AutoTokenizer.from_pretrained
  use_fast: true
  # Note: We could interpolate this value with `${/algorithm/network/pretrained_model_name_or_path}`
  # to avoid duplicating a value, but this also makes it harder to use this by itself or with
  # another algorithm.
  pretrained_model_name_or_path: albert-base-v2
  cache_dir: ${..data_dir}
  trust_remote_code: true
num_classes: 2
max_seq_length: 128
train_batch_size: 32
eval_batch_size: 32
