_target_: project.datamodules.HFDataModule
data_dir: ${oc.env:SCRATCH,/}/data
tokenizer:
  _target_: transformers.models.auto.tokenization_auto.AutoTokenizer.from_pretrained
  use_fast: true
  pretrained_model_name_or_path: ${/algorithm/network/pretrained_model_name_or_path}
  cache_dir: ${.data_dir}
  trust_remote_code: true

hf_dataset_path: ???
task_name: ???
