# yaml-language-server: $schema=../../../.schemas/datamodule_imagenet32_schema.json
defaults:
  - vision
  - _self_
_target_: project.datamodules.ImageNet32DataModule
data_dir: ${constant:SCRATCH}
val_split: -1
num_images_per_val_class: 50
normalize: True
train_transforms:
  _target_: project.datamodules.image_classification.imagenet32.imagenet32_train_transforms
