# yaml-language-server: $schema=../../../.schemas/datamodule_inaturalist_schema.json
defaults:
  - vision
  - _self_
_target_: project.datamodules.INaturalistDataModule
version: "2021_train"
target_type: "full"
