_target_: project.datamodules.HFDataModule
tokenizer: huggingface:wikitext/wikitext-103-v1
hf_dataset_path: huggingface:wikitext/wikitext-103-v1
task_name: null
# max_seq_length: 128
train_batch_size: 32
eval_batch_size: 32
