# @package _global_.hydra

defaults:
  - mila.yaml

mode: MULTIRUN

launcher:
  executor:
    cluster_hostname: narval
    internet_access_on_compute_nodes: false
  account: rrg-bengioy-ad # Replace this with your DRAC allocation!
