
_target_: project.algorithms.llm_finetuning_example.LLMFinetuningExample
network_config:
  _target_: project.algorithms.llm_finetuning_example.NetworkConfig
  _recursive_: false
  _convert_: object
  pretrained_model_name_or_path: facebook/opt-1.3b
  # device_map: auto  # use this (and run `uv add accelerate`) for multi-GPU jobs
tokenizer_config:
  _target_: project.algorithms.llm_finetuning_example.TokenizerConfig
  _recursive_: false
  _convert_: object
  pretrained_model_name_or_path: facebook/opt-1.3b
  use_fast: true
  trust_remote_code: true
dataset_config:
  _target_: project.algorithms.llm_finetuning_example.DatasetConfig
  dataset_path: wikitext
  dataset_name: wikitext-103-v1
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  block_size: 128
learning_rate: 2e-5
adam_epsilon: 1e-8
warmup_steps: 0
weight_decay: 0
init_seed: 42
