defaults:
  - wandb
wandb:
  project: "ResearchTemplate"
  # TODO: Use the Orion trial name?
  name: ${oc.env:SLURM_JOB_ID}_${oc.env:SLURM_PROCID}
  save_dir: "${hydra:runtime.output_dir}"
  offline: false # set True to store all logs only locally
  id: ${oc.env:SLURM_JOB_ID}_${oc.env:SLURM_ARRAY_TASK_ID,}_${oc.env:SLURM_PROCID} # pass correct id to resume experiment!
  # entity: ""  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  group: ${oc.env:SLURM_JOB_ID}
  # tags: ["${name}"]
